# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ComputeGraph.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Tensor_pb2 as Tensor__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ComputeGraph.proto',
  package='icdl_proto',
  syntax='proto3',
  serialized_pb=_b('\n\x12\x43omputeGraph.proto\x12\nicdl_proto\x1a\x0cTensor.proto\"\x95\x01\n\x0bGraphParams\x12>\n\x0cgraph_params\x18\x01 \x03(\x0b\x32(.icdl_proto.GraphParams.GraphParamsEntry\x1a\x46\n\x10GraphParamsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12!\n\x05value\x18\x02 \x01(\x0b\x32\x12.icdl_proto.Tensor:\x02\x38\x01\x62\x06proto3')
  ,
  dependencies=[Tensor__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_GRAPHPARAMS_GRAPHPARAMSENTRY = _descriptor.Descriptor(
  name='GraphParamsEntry',
  full_name='icdl_proto.GraphParams.GraphParamsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='icdl_proto.GraphParams.GraphParamsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='icdl_proto.GraphParams.GraphParamsEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=128,
  serialized_end=198,
)

_GRAPHPARAMS = _descriptor.Descriptor(
  name='GraphParams',
  full_name='icdl_proto.GraphParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='graph_params', full_name='icdl_proto.GraphParams.graph_params', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_GRAPHPARAMS_GRAPHPARAMSENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=198,
)

_GRAPHPARAMS_GRAPHPARAMSENTRY.fields_by_name['value'].message_type = Tensor__pb2._TENSOR
_GRAPHPARAMS_GRAPHPARAMSENTRY.containing_type = _GRAPHPARAMS
_GRAPHPARAMS.fields_by_name['graph_params'].message_type = _GRAPHPARAMS_GRAPHPARAMSENTRY
DESCRIPTOR.message_types_by_name['GraphParams'] = _GRAPHPARAMS

GraphParams = _reflection.GeneratedProtocolMessageType('GraphParams', (_message.Message,), dict(

  GraphParamsEntry = _reflection.GeneratedProtocolMessageType('GraphParamsEntry', (_message.Message,), dict(
    DESCRIPTOR = _GRAPHPARAMS_GRAPHPARAMSENTRY,
    __module__ = 'ComputeGraph_pb2'
    # @@protoc_insertion_point(class_scope:icdl_proto.GraphParams.GraphParamsEntry)
    ))
  ,
  DESCRIPTOR = _GRAPHPARAMS,
  __module__ = 'ComputeGraph_pb2'
  # @@protoc_insertion_point(class_scope:icdl_proto.GraphParams)
  ))
_sym_db.RegisterMessage(GraphParams)
_sym_db.RegisterMessage(GraphParams.GraphParamsEntry)


_GRAPHPARAMS_GRAPHPARAMSENTRY.has_options = True
_GRAPHPARAMS_GRAPHPARAMSENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
# @@protoc_insertion_point(module_scope)
