# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Tensor.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Tensor.proto',
  package='icdl_proto',
  syntax='proto3',
  serialized_pb=_b('\n\x0cTensor.proto\x12\nicdl_proto\"~\n\x11\x46ixpointRepresent\x12\x12\n\ntotal_bits\x18\x01 \x03(\r\x12\x11\n\tis_signed\x18\x02 \x03(\x08\x12\x1c\n\x14\x66rac_point_locations\x18\x03 \x03(\x05\x12\x0f\n\x07scalars\x18\x04 \x03(\x02\x12\x13\n\x0bzero_points\x18\x05 \x03(\x05\"e\n\x13\x46loatpointRepresent\x12\x12\n\ntotal_bits\x18\x01 \x01(\r\x12\x11\n\tis_signed\x18\x02 \x01(\x08\x12\x10\n\x08\x65xp_bits\x18\x03 \x01(\r\x12\x15\n\rmantissa_bits\x18\x04 \x01(\r\"\xa1\x02\n\x14TensorDataDescriptor\x12>\n\x05\x64type\x18\x01 \x01(\x0e\x32/.icdl_proto.TensorDataDescriptor.TensorDataType\x12\x32\n\tfix_point\x18\x02 \x01(\x0b\x32\x1d.icdl_proto.FixpointRepresentH\x00\x12\x34\n\tflo_point\x18\x03 \x01(\x0b\x32\x1f.icdl_proto.FloatpointRepresentH\x00\"M\n\x0eTensorDataType\x12\x0c\n\x08\x46LOAT_32\x10\x00\x12\x0c\n\x08\x46LOAT_16\x10\x01\x12\x0c\n\x08\x46IXPOINT\x10\x02\x12\x11\n\rINVALID_DTYPE\x10\x03\x42\x10\n\x0e\x64\x61ta_represent\"X\n\rTensorStorage\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x39\n\x0f\x64\x61ta_descriptor\x18\x02 \x01(\x0b\x32 .icdl_proto.TensorDataDescriptor\"\xcd\x01\n\x06Tensor\x12*\n\x07storage\x18\x02 \x01(\x0b\x32\x19.icdl_proto.TensorStorage\x12\x13\n\x0btensor_size\x18\x03 \x03(\x04\x12\x36\n\nmem_layout\x18\x04 \x01(\x0e\x32\".icdl_proto.Tensor.TensorMemLayout\"J\n\x0fTensorMemLayout\x12\x10\n\x0c\x44\x45NSE_LAYOUT\x10\x00\x12\x11\n\rSPARSE_LAYOUT\x10\x01\x12\x12\n\x0eINVALID_LAYOUT\x10\x02\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_TENSORDATADESCRIPTOR_TENSORDATATYPE = _descriptor.EnumDescriptor(
  name='TensorDataType',
  full_name='icdl_proto.TensorDataDescriptor.TensorDataType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='FLOAT_32', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FLOAT_16', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FIXPOINT', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INVALID_DTYPE', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=454,
  serialized_end=531,
)
_sym_db.RegisterEnumDescriptor(_TENSORDATADESCRIPTOR_TENSORDATATYPE)

_TENSOR_TENSORMEMLAYOUT = _descriptor.EnumDescriptor(
  name='TensorMemLayout',
  full_name='icdl_proto.Tensor.TensorMemLayout',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DENSE_LAYOUT', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SPARSE_LAYOUT', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INVALID_LAYOUT', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=773,
  serialized_end=847,
)
_sym_db.RegisterEnumDescriptor(_TENSOR_TENSORMEMLAYOUT)


_FIXPOINTREPRESENT = _descriptor.Descriptor(
  name='FixpointRepresent',
  full_name='icdl_proto.FixpointRepresent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='total_bits', full_name='icdl_proto.FixpointRepresent.total_bits', index=0,
      number=1, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='is_signed', full_name='icdl_proto.FixpointRepresent.is_signed', index=1,
      number=2, type=8, cpp_type=7, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='frac_point_locations', full_name='icdl_proto.FixpointRepresent.frac_point_locations', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='scalars', full_name='icdl_proto.FixpointRepresent.scalars', index=3,
      number=4, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='zero_points', full_name='icdl_proto.FixpointRepresent.zero_points', index=4,
      number=5, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=154,
)


_FLOATPOINTREPRESENT = _descriptor.Descriptor(
  name='FloatpointRepresent',
  full_name='icdl_proto.FloatpointRepresent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='total_bits', full_name='icdl_proto.FloatpointRepresent.total_bits', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='is_signed', full_name='icdl_proto.FloatpointRepresent.is_signed', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='exp_bits', full_name='icdl_proto.FloatpointRepresent.exp_bits', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mantissa_bits', full_name='icdl_proto.FloatpointRepresent.mantissa_bits', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=156,
  serialized_end=257,
)


_TENSORDATADESCRIPTOR = _descriptor.Descriptor(
  name='TensorDataDescriptor',
  full_name='icdl_proto.TensorDataDescriptor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dtype', full_name='icdl_proto.TensorDataDescriptor.dtype', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fix_point', full_name='icdl_proto.TensorDataDescriptor.fix_point', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='flo_point', full_name='icdl_proto.TensorDataDescriptor.flo_point', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _TENSORDATADESCRIPTOR_TENSORDATATYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='data_represent', full_name='icdl_proto.TensorDataDescriptor.data_represent',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=260,
  serialized_end=549,
)


_TENSORSTORAGE = _descriptor.Descriptor(
  name='TensorStorage',
  full_name='icdl_proto.TensorStorage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='icdl_proto.TensorStorage.data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data_descriptor', full_name='icdl_proto.TensorStorage.data_descriptor', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=551,
  serialized_end=639,
)


_TENSOR = _descriptor.Descriptor(
  name='Tensor',
  full_name='icdl_proto.Tensor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='storage', full_name='icdl_proto.Tensor.storage', index=0,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tensor_size', full_name='icdl_proto.Tensor.tensor_size', index=1,
      number=3, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mem_layout', full_name='icdl_proto.Tensor.mem_layout', index=2,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _TENSOR_TENSORMEMLAYOUT,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=642,
  serialized_end=847,
)

_TENSORDATADESCRIPTOR.fields_by_name['dtype'].enum_type = _TENSORDATADESCRIPTOR_TENSORDATATYPE
_TENSORDATADESCRIPTOR.fields_by_name['fix_point'].message_type = _FIXPOINTREPRESENT
_TENSORDATADESCRIPTOR.fields_by_name['flo_point'].message_type = _FLOATPOINTREPRESENT
_TENSORDATADESCRIPTOR_TENSORDATATYPE.containing_type = _TENSORDATADESCRIPTOR
_TENSORDATADESCRIPTOR.oneofs_by_name['data_represent'].fields.append(
  _TENSORDATADESCRIPTOR.fields_by_name['fix_point'])
_TENSORDATADESCRIPTOR.fields_by_name['fix_point'].containing_oneof = _TENSORDATADESCRIPTOR.oneofs_by_name['data_represent']
_TENSORDATADESCRIPTOR.oneofs_by_name['data_represent'].fields.append(
  _TENSORDATADESCRIPTOR.fields_by_name['flo_point'])
_TENSORDATADESCRIPTOR.fields_by_name['flo_point'].containing_oneof = _TENSORDATADESCRIPTOR.oneofs_by_name['data_represent']
_TENSORSTORAGE.fields_by_name['data_descriptor'].message_type = _TENSORDATADESCRIPTOR
_TENSOR.fields_by_name['storage'].message_type = _TENSORSTORAGE
_TENSOR.fields_by_name['mem_layout'].enum_type = _TENSOR_TENSORMEMLAYOUT
_TENSOR_TENSORMEMLAYOUT.containing_type = _TENSOR
DESCRIPTOR.message_types_by_name['FixpointRepresent'] = _FIXPOINTREPRESENT
DESCRIPTOR.message_types_by_name['FloatpointRepresent'] = _FLOATPOINTREPRESENT
DESCRIPTOR.message_types_by_name['TensorDataDescriptor'] = _TENSORDATADESCRIPTOR
DESCRIPTOR.message_types_by_name['TensorStorage'] = _TENSORSTORAGE
DESCRIPTOR.message_types_by_name['Tensor'] = _TENSOR

FixpointRepresent = _reflection.GeneratedProtocolMessageType('FixpointRepresent', (_message.Message,), dict(
  DESCRIPTOR = _FIXPOINTREPRESENT,
  __module__ = 'Tensor_pb2'
  # @@protoc_insertion_point(class_scope:icdl_proto.FixpointRepresent)
  ))
_sym_db.RegisterMessage(FixpointRepresent)

FloatpointRepresent = _reflection.GeneratedProtocolMessageType('FloatpointRepresent', (_message.Message,), dict(
  DESCRIPTOR = _FLOATPOINTREPRESENT,
  __module__ = 'Tensor_pb2'
  # @@protoc_insertion_point(class_scope:icdl_proto.FloatpointRepresent)
  ))
_sym_db.RegisterMessage(FloatpointRepresent)

TensorDataDescriptor = _reflection.GeneratedProtocolMessageType('TensorDataDescriptor', (_message.Message,), dict(
  DESCRIPTOR = _TENSORDATADESCRIPTOR,
  __module__ = 'Tensor_pb2'
  # @@protoc_insertion_point(class_scope:icdl_proto.TensorDataDescriptor)
  ))
_sym_db.RegisterMessage(TensorDataDescriptor)

TensorStorage = _reflection.GeneratedProtocolMessageType('TensorStorage', (_message.Message,), dict(
  DESCRIPTOR = _TENSORSTORAGE,
  __module__ = 'Tensor_pb2'
  # @@protoc_insertion_point(class_scope:icdl_proto.TensorStorage)
  ))
_sym_db.RegisterMessage(TensorStorage)

Tensor = _reflection.GeneratedProtocolMessageType('Tensor', (_message.Message,), dict(
  DESCRIPTOR = _TENSOR,
  __module__ = 'Tensor_pb2'
  # @@protoc_insertion_point(class_scope:icdl_proto.Tensor)
  ))
_sym_db.RegisterMessage(Tensor)


# @@protoc_insertion_point(module_scope)
