// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ComputeGraph.proto

#include "ComputeGraph.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

extern PROTOBUF_INTERNAL_EXPORT_ComputeGraph_2eproto ::google::protobuf::internal::SCCInfo<1> scc_info_GraphParams_GraphParamsEntry_DoNotUse_ComputeGraph_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_Tensor_2eproto ::google::protobuf::internal::SCCInfo<1> scc_info_Tensor_Tensor_2eproto;
namespace icdl_proto {
class GraphParams_GraphParamsEntry_DoNotUseDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<GraphParams_GraphParamsEntry_DoNotUse> _instance;
} _GraphParams_GraphParamsEntry_DoNotUse_default_instance_;
class GraphParamsDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<GraphParams> _instance;
} _GraphParams_default_instance_;
}  // namespace icdl_proto
static void InitDefaultsGraphParams_GraphParamsEntry_DoNotUse_ComputeGraph_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::icdl_proto::_GraphParams_GraphParamsEntry_DoNotUse_default_instance_;
    new (ptr) ::icdl_proto::GraphParams_GraphParamsEntry_DoNotUse();
  }
  ::icdl_proto::GraphParams_GraphParamsEntry_DoNotUse::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_GraphParams_GraphParamsEntry_DoNotUse_ComputeGraph_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsGraphParams_GraphParamsEntry_DoNotUse_ComputeGraph_2eproto}, {
      &scc_info_Tensor_Tensor_2eproto.base,}};

static void InitDefaultsGraphParams_ComputeGraph_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::icdl_proto::_GraphParams_default_instance_;
    new (ptr) ::icdl_proto::GraphParams();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::icdl_proto::GraphParams::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_GraphParams_ComputeGraph_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsGraphParams_ComputeGraph_2eproto}, {
      &scc_info_GraphParams_GraphParamsEntry_DoNotUse_ComputeGraph_2eproto.base,}};

void InitDefaults_ComputeGraph_2eproto() {
  ::google::protobuf::internal::InitSCC(&scc_info_GraphParams_GraphParamsEntry_DoNotUse_ComputeGraph_2eproto.base);
  ::google::protobuf::internal::InitSCC(&scc_info_GraphParams_ComputeGraph_2eproto.base);
}

::google::protobuf::Metadata file_level_metadata_ComputeGraph_2eproto[2];
constexpr ::google::protobuf::EnumDescriptor const** file_level_enum_descriptors_ComputeGraph_2eproto = nullptr;
constexpr ::google::protobuf::ServiceDescriptor const** file_level_service_descriptors_ComputeGraph_2eproto = nullptr;

const ::google::protobuf::uint32 TableStruct_ComputeGraph_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::icdl_proto::GraphParams_GraphParamsEntry_DoNotUse, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::icdl_proto::GraphParams_GraphParamsEntry_DoNotUse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::icdl_proto::GraphParams_GraphParamsEntry_DoNotUse, key_),
  PROTOBUF_FIELD_OFFSET(::icdl_proto::GraphParams_GraphParamsEntry_DoNotUse, value_),
  0,
  1,
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::icdl_proto::GraphParams, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::icdl_proto::GraphParams, graph_params_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 7, sizeof(::icdl_proto::GraphParams_GraphParamsEntry_DoNotUse)},
  { 9, -1, sizeof(::icdl_proto::GraphParams)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::icdl_proto::_GraphParams_GraphParamsEntry_DoNotUse_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::icdl_proto::_GraphParams_default_instance_),
};

::google::protobuf::internal::AssignDescriptorsTable assign_descriptors_table_ComputeGraph_2eproto = {
  {}, AddDescriptors_ComputeGraph_2eproto, "ComputeGraph.proto", schemas,
  file_default_instances, TableStruct_ComputeGraph_2eproto::offsets,
  file_level_metadata_ComputeGraph_2eproto, 2, file_level_enum_descriptors_ComputeGraph_2eproto, file_level_service_descriptors_ComputeGraph_2eproto,
};

const char descriptor_table_protodef_ComputeGraph_2eproto[] =
  "\n\022ComputeGraph.proto\022\nicdl_proto\032\014Tensor"
  ".proto\"\225\001\n\013GraphParams\022>\n\014graph_params\030\001"
  " \003(\0132(.icdl_proto.GraphParams.GraphParam"
  "sEntry\032F\n\020GraphParamsEntry\022\013\n\003key\030\001 \001(\t\022"
  "!\n\005value\030\002 \001(\0132\022.icdl_proto.Tensor:\0028\001b\006"
  "proto3"
  ;
::google::protobuf::internal::DescriptorTable descriptor_table_ComputeGraph_2eproto = {
  false, InitDefaults_ComputeGraph_2eproto, 
  descriptor_table_protodef_ComputeGraph_2eproto,
  "ComputeGraph.proto", &assign_descriptors_table_ComputeGraph_2eproto, 206,
};

void AddDescriptors_ComputeGraph_2eproto() {
  static constexpr ::google::protobuf::internal::InitFunc deps[1] =
  {
    ::AddDescriptors_Tensor_2eproto,
  };
 ::google::protobuf::internal::AddDescriptors(&descriptor_table_ComputeGraph_2eproto, deps, 1);
}

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_ComputeGraph_2eproto = []() { AddDescriptors_ComputeGraph_2eproto(); return true; }();
namespace icdl_proto {

// ===================================================================

GraphParams_GraphParamsEntry_DoNotUse::GraphParams_GraphParamsEntry_DoNotUse() {}
GraphParams_GraphParamsEntry_DoNotUse::GraphParams_GraphParamsEntry_DoNotUse(::google::protobuf::Arena* arena)
    : SuperType(arena) {}
void GraphParams_GraphParamsEntry_DoNotUse::MergeFrom(const GraphParams_GraphParamsEntry_DoNotUse& other) {
  MergeFromInternal(other);
}
::google::protobuf::Metadata GraphParams_GraphParamsEntry_DoNotUse::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_ComputeGraph_2eproto);
  return ::file_level_metadata_ComputeGraph_2eproto[0];
}
void GraphParams_GraphParamsEntry_DoNotUse::MergeFrom(
    const ::google::protobuf::Message& other) {
  ::google::protobuf::Message::MergeFrom(other);
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool GraphParams_GraphParamsEntry_DoNotUse::_ParseMap(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx) {
  using MF = ::google::protobuf::internal::MapField<
      GraphParams_GraphParamsEntry_DoNotUse, EntryKeyType, EntryValueType,
      kEntryKeyFieldType, kEntryValueFieldType,
      kEntryDefaultEnumValue>;
  auto mf = static_cast<MF*>(object);
  Parser<MF, ::google::protobuf::Map<EntryKeyType, EntryValueType>> parser(mf);
#define DO_(x) if (!(x)) return false
  DO_(parser.ParseMap(begin, end));
  DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
    parser.key().data(), static_cast<int>(parser.key().length()),
    ::google::protobuf::internal::WireFormatLite::PARSE,
    "icdl_proto.GraphParams.GraphParamsEntry.key"));
#undef DO_
  return true;
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER


// ===================================================================

void GraphParams::InitAsDefaultInstance() {
}
class GraphParams::HasBitSetters {
 public:
};

void GraphParams::clear_graph_params() {
  graph_params_.Clear();
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int GraphParams::kGraphParamsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

GraphParams::GraphParams()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:icdl_proto.GraphParams)
}
GraphParams::GraphParams(const GraphParams& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  graph_params_.MergeFrom(from.graph_params_);
  // @@protoc_insertion_point(copy_constructor:icdl_proto.GraphParams)
}

void GraphParams::SharedCtor() {
  ::google::protobuf::internal::InitSCC(
      &scc_info_GraphParams_ComputeGraph_2eproto.base);
}

GraphParams::~GraphParams() {
  // @@protoc_insertion_point(destructor:icdl_proto.GraphParams)
  SharedDtor();
}

void GraphParams::SharedDtor() {
}

void GraphParams::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const GraphParams& GraphParams::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_GraphParams_ComputeGraph_2eproto.base);
  return *internal_default_instance();
}


void GraphParams::Clear() {
// @@protoc_insertion_point(message_clear_start:icdl_proto.GraphParams)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  graph_params_.Clear();
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* GraphParams::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<GraphParams*>(object);
  ::google::protobuf::uint32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // map<string, .icdl_proto.Tensor> graph_params = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 10) goto handle_unusual;
        do {
          ptr = ::google::protobuf::io::Parse32(ptr, &size);
          GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
          parser_till_end = ::google::protobuf::internal::SlowMapEntryParser;
          auto parse_map = ::icdl_proto::GraphParams_GraphParamsEntry_DoNotUse::_ParseMap;
          ctx->extra_parse_data().payload.clear();
          ctx->extra_parse_data().parse_map = parse_map;
          object = &msg->graph_params_;
          if (size > end - ptr) goto len_delim_till_end;
          auto newend = ptr + size;
          GOOGLE_PROTOBUF_PARSER_ASSERT(parse_map(ptr, newend, object, ctx));
          ptr = newend;
          if (ptr >= end) break;
        } while ((::google::protobuf::io::UnalignedLoad<::google::protobuf::uint64>(ptr) & 255) == 10 && (ptr += 1));
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
len_delim_till_end:
  return ctx->StoreAndTailCall(ptr, end, {_InternalParse, msg},
                               {parser_till_end, object}, size);
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool GraphParams::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:icdl_proto.GraphParams)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // map<string, .icdl_proto.Tensor> graph_params = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (10 & 0xFF)) {
          GraphParams_GraphParamsEntry_DoNotUse::Parser< ::google::protobuf::internal::MapField<
              GraphParams_GraphParamsEntry_DoNotUse,
              ::std::string, ::icdl_proto::Tensor,
              ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
              ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
              0 >,
            ::google::protobuf::Map< ::std::string, ::icdl_proto::Tensor > > parser(&graph_params_);
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
              input, &parser));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            parser.key().data(), static_cast<int>(parser.key().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "icdl_proto.GraphParams.GraphParamsEntry.key"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:icdl_proto.GraphParams)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:icdl_proto.GraphParams)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void GraphParams::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:icdl_proto.GraphParams)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // map<string, .icdl_proto.Tensor> graph_params = 1;
  if (!this->graph_params().empty()) {
    typedef ::google::protobuf::Map< ::std::string, ::icdl_proto::Tensor >::const_pointer
        ConstPtr;
    typedef ConstPtr SortItem;
    typedef ::google::protobuf::internal::CompareByDerefFirst<SortItem> Less;
    struct Utf8Check {
      static void Check(ConstPtr p) {
        ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          p->first.data(), static_cast<int>(p->first.length()),
          ::google::protobuf::internal::WireFormatLite::SERIALIZE,
          "icdl_proto.GraphParams.GraphParamsEntry.key");
      }
    };

    if (output->IsSerializationDeterministic() &&
        this->graph_params().size() > 1) {
      ::std::unique_ptr<SortItem[]> items(
          new SortItem[this->graph_params().size()]);
      typedef ::google::protobuf::Map< ::std::string, ::icdl_proto::Tensor >::size_type size_type;
      size_type n = 0;
      for (::google::protobuf::Map< ::std::string, ::icdl_proto::Tensor >::const_iterator
          it = this->graph_params().begin();
          it != this->graph_params().end(); ++it, ++n) {
        items[static_cast<ptrdiff_t>(n)] = SortItem(&*it);
      }
      ::std::sort(&items[0], &items[static_cast<ptrdiff_t>(n)], Less());
      ::std::unique_ptr<GraphParams_GraphParamsEntry_DoNotUse> entry;
      for (size_type i = 0; i < n; i++) {
        entry.reset(graph_params_.NewEntryWrapper(items[static_cast<ptrdiff_t>(i)]->first, items[static_cast<ptrdiff_t>(i)]->second));
        ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(1, *entry, output);
        Utf8Check::Check(&(*items[static_cast<ptrdiff_t>(i)]));
      }
    } else {
      ::std::unique_ptr<GraphParams_GraphParamsEntry_DoNotUse> entry;
      for (::google::protobuf::Map< ::std::string, ::icdl_proto::Tensor >::const_iterator
          it = this->graph_params().begin();
          it != this->graph_params().end(); ++it) {
        entry.reset(graph_params_.NewEntryWrapper(it->first, it->second));
        ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(1, *entry, output);
        Utf8Check::Check(&(*it));
      }
    }
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:icdl_proto.GraphParams)
}

::google::protobuf::uint8* GraphParams::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:icdl_proto.GraphParams)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // map<string, .icdl_proto.Tensor> graph_params = 1;
  if (!this->graph_params().empty()) {
    typedef ::google::protobuf::Map< ::std::string, ::icdl_proto::Tensor >::const_pointer
        ConstPtr;
    typedef ConstPtr SortItem;
    typedef ::google::protobuf::internal::CompareByDerefFirst<SortItem> Less;
    struct Utf8Check {
      static void Check(ConstPtr p) {
        ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          p->first.data(), static_cast<int>(p->first.length()),
          ::google::protobuf::internal::WireFormatLite::SERIALIZE,
          "icdl_proto.GraphParams.GraphParamsEntry.key");
      }
    };

    if (false &&
        this->graph_params().size() > 1) {
      ::std::unique_ptr<SortItem[]> items(
          new SortItem[this->graph_params().size()]);
      typedef ::google::protobuf::Map< ::std::string, ::icdl_proto::Tensor >::size_type size_type;
      size_type n = 0;
      for (::google::protobuf::Map< ::std::string, ::icdl_proto::Tensor >::const_iterator
          it = this->graph_params().begin();
          it != this->graph_params().end(); ++it, ++n) {
        items[static_cast<ptrdiff_t>(n)] = SortItem(&*it);
      }
      ::std::sort(&items[0], &items[static_cast<ptrdiff_t>(n)], Less());
      ::std::unique_ptr<GraphParams_GraphParamsEntry_DoNotUse> entry;
      for (size_type i = 0; i < n; i++) {
        entry.reset(graph_params_.NewEntryWrapper(items[static_cast<ptrdiff_t>(i)]->first, items[static_cast<ptrdiff_t>(i)]->second));
        target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessageNoVirtualToArray(1, *entry, target);
        Utf8Check::Check(&(*items[static_cast<ptrdiff_t>(i)]));
      }
    } else {
      ::std::unique_ptr<GraphParams_GraphParamsEntry_DoNotUse> entry;
      for (::google::protobuf::Map< ::std::string, ::icdl_proto::Tensor >::const_iterator
          it = this->graph_params().begin();
          it != this->graph_params().end(); ++it) {
        entry.reset(graph_params_.NewEntryWrapper(it->first, it->second));
        target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessageNoVirtualToArray(1, *entry, target);
        Utf8Check::Check(&(*it));
      }
    }
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:icdl_proto.GraphParams)
  return target;
}

size_t GraphParams::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:icdl_proto.GraphParams)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // map<string, .icdl_proto.Tensor> graph_params = 1;
  total_size += 1 *
      ::google::protobuf::internal::FromIntSize(this->graph_params_size());
  {
    ::std::unique_ptr<GraphParams_GraphParamsEntry_DoNotUse> entry;
    for (::google::protobuf::Map< ::std::string, ::icdl_proto::Tensor >::const_iterator
        it = this->graph_params().begin();
        it != this->graph_params().end(); ++it) {
      entry.reset(graph_params_.NewEntryWrapper(it->first, it->second));
      total_size += ::google::protobuf::internal::WireFormatLite::
          MessageSizeNoVirtual(*entry);
    }
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void GraphParams::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:icdl_proto.GraphParams)
  GOOGLE_DCHECK_NE(&from, this);
  const GraphParams* source =
      ::google::protobuf::DynamicCastToGenerated<GraphParams>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:icdl_proto.GraphParams)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:icdl_proto.GraphParams)
    MergeFrom(*source);
  }
}

void GraphParams::MergeFrom(const GraphParams& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:icdl_proto.GraphParams)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  graph_params_.MergeFrom(from.graph_params_);
}

void GraphParams::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:icdl_proto.GraphParams)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void GraphParams::CopyFrom(const GraphParams& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:icdl_proto.GraphParams)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GraphParams::IsInitialized() const {
  return true;
}

void GraphParams::Swap(GraphParams* other) {
  if (other == this) return;
  InternalSwap(other);
}
void GraphParams::InternalSwap(GraphParams* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  graph_params_.Swap(&other->graph_params_);
}

::google::protobuf::Metadata GraphParams::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_ComputeGraph_2eproto);
  return ::file_level_metadata_ComputeGraph_2eproto[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace icdl_proto
namespace google {
namespace protobuf {
template<> PROTOBUF_NOINLINE ::icdl_proto::GraphParams_GraphParamsEntry_DoNotUse* Arena::CreateMaybeMessage< ::icdl_proto::GraphParams_GraphParamsEntry_DoNotUse >(Arena* arena) {
  return Arena::CreateInternal< ::icdl_proto::GraphParams_GraphParamsEntry_DoNotUse >(arena);
}
template<> PROTOBUF_NOINLINE ::icdl_proto::GraphParams* Arena::CreateMaybeMessage< ::icdl_proto::GraphParams >(Arena* arena) {
  return Arena::CreateInternal< ::icdl_proto::GraphParams >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
